### ISSUE TITLE
Outputs of the four scripts

### ISSUE THREAD

**Issue by fwu03** [UBC-MDS/DSCI522_sreya_fwu#18]
01_data-clean.py: A clean dataset under "data/crime_1617_clean_data.csv"
02_data-EDA.R: EDA pngs under "img/crime_arrest_2016.png", "img/crime_arrest_2017.png","crime_loc_bar.png","crime_type_bar.png"
03_data-analysis.py: csv files under "results/crime_1617_decisiontree_model.sav", "crime_1617_decisiontree_result.csv", "crime_1617_decisiontree_cvscores.csv" (i.e. 10-fold cross-validation results), "crime_1617_decisiontree_featuresimportance.csv" (i.e. features importance results)
04_data-summary.py: decistion tree picture under "img/Crime_tree.pdf"

**Comment by sreyaguha** [comment]
Thanks! I'll make the report accordingly :)
