### ISSUE TITLE
Milestone 2 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI522_sreya_fwu#40]
- Figure 4 image does not display in the report (md format).
- You found the two most important features and you gave each one an "importance" number. So how important are these features? Also, discuss what this implies. Discuss the results a little, don't just state the results.

_Originally posted by @aimirza in https://github.com/UBC-MDS/DSCI522_sreya_fwu/issue_comments#issuecomment-444758601_

**Comment by sreyaguha** [comment]
Changes corrected in the latest release.
